/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.lox.Lox;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        try {
            Lox.main(new String[]{});
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
